name: Deploy to EC2 via SSH

on:

  push:

    branches:

      - main

jobs:

  deploy:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout repository

      uses: actions/checkout@v3

    - name: Copy files to EC2

      uses: appleboy/scp-action@master

      with:

        host: ${{ secrets.EC2_HOST }}

        username: ec2-user

        key: ${{ secrets.EC2_KEY }}

        source: "."

        target: "/home/ec2-user/app"

    - name: Deploy on EC2

      uses: appleboy/ssh-action@master

      with:

        host: ${{ secrets.EC2_HOST }}

        username: ec2-user

        key: ${{ secrets.EC2_KEY }}

        script: |

          cd app

          docker stop flask_app || true

          docker rm flask_app || true

          docker build -t flask_app .

          docker run -d -p 5000:5000 --name flask_app flask_app
 